name: nordigen_integration
description: Dart/Flutter Package for Nordigen EU PSD2 AISP Integration, with relevant Data Models.
version: 1.0.2
homepage: https://github.com/Dhi13man/nordigen_integration

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.3
  meta: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher:
  lint: ^1.5.3
  
flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
