name: nordigen_integration
description: Dart/Flutter Package for Nordigen's EU PSD2 AISP Banking API Integration, with relevant Data Models.
version: 1.7.0
homepage: https://github.com/Dhi13man/nordigen_integration

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
